#!/usr/bin/env sh
# Creates the gitignored Config.kt the Android target needs to compile.
#
# Like its iOS counterpart, the repo does not build from a clean clone without
# it: Config.kt is generated by Rork and gitignored, while data/AiService.kt
# references it.
#
# The package and destination are derived from MainActivity.kt rather than
# hardcoded, so this keeps working after a package rename.
#
# Safe to re-run: it never overwrites an existing Config.kt.

set -e

DIR="$(cd "$(dirname "$0")" && pwd)"
SRC="$DIR/app/src/main/java"

MAIN="$(find "$SRC" -name MainActivity.kt -print | head -1)"
if [ -z "$MAIN" ]; then
  echo "Could not find MainActivity.kt under $SRC - is this the right checkout?" >&2
  exit 1
fi

PKG_DIR="$(dirname "$MAIN")"
PKG="$(sed -n 's/^package \([A-Za-z0-9_.]*\).*/\1/p' "$MAIN" | head -1)"
if [ -z "$PKG" ]; then
  echo "Could not read a package declaration from $MAIN" >&2
  exit 1
fi

TARGET="$PKG_DIR/Config.kt"
if [ -f "$TARGET" ]; then
  echo "Config.kt already exists - leaving it alone."
  exit 0
fi

sed "s/^package PACKAGE_PLACEHOLDER$/package $PKG/" "$DIR/Config.kt.example" \
  | sed '1,/^package /{/^\/\//d;}' > "$TARGET"

echo "Created ${TARGET#"$DIR"/} with package $PKG"
echo
echo "Next: paste your Rork toolkit key into it, then open android/ in Android Studio."
echo "Leaving the key empty is fine for a first build."
