#!/usr/bin/env sh
# Creates the gitignored Config.swift the iOS target needs to compile.
#
# The repo does not build from a clean clone without it: Config.swift is
# generated by Rork and gitignored, so a fresh checkout is missing a file two
# source files reference. This is the first thing anyone hits on a new machine.
#
# Safe to re-run: it never overwrites an existing Config.swift.

set -e

DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET="$DIR/ModernBodyFoodScanner/Config.swift"
TEMPLATE="$DIR/Config.swift.example"

if [ -f "$TARGET" ]; then
  echo "Config.swift already exists - leaving it alone."
  exit 0
fi

sed '1,/^import Foundation$/{/^\/\//d;}' "$TEMPLATE" > "$TARGET"
echo "Created ModernBodyFoodScanner/Config.swift"
echo
echo "Next: paste your Rork toolkit key into it, then open the Xcode project."
echo "Leaving the key empty is fine for a first build - the app will report"
echo "\"AI scanning isn't available in this build yet\" instead of failing oddly."
